application: beardo-project
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
  - warmup

handlers:
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico
  - url: /static/
    secure: always
    static_dir: static/
    http_headers:
      X-Frame-Options: "DENY"
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
  - url: /.*
    script: nacelle.app.wsgi
    secure: always

libraries:
  - name: jinja2
    version: "2.6"
  - name: webapp2
    version: "2.5.2"

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - Makefile
  - app.yaml
  - run-tests.py
  - tests/.*
